apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proteus-gateway
  namespace: proteus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - proteus-api.live
      secretName: proteus-gateway-tls
  rules:
    - host: proteus-api.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proteus-gateway
                port:
                  number: 80