
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTnR0VHN2ZGJpdTB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1Ua3hPVEEyTVRsYUZ3MHpOakF5TVRjeE9URXhNVGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURtb05ybnEvRGdJS3ptWlZMZUNwNkt5WEVHU3JCSmVYUUJ2ckhRWlE0NFRlZVZDWEZLV3J4eFhyYzkKRkkwMDVpWnlXK29DYUJENDR5R1lvTHAzZnhjTUtDcXZmMDdCSkJiTDQ0VE00Zlc2aVdqRFBxVHlHL2U1VWlqQwoxdUZmM3NrWFVMMXlYMFVXa3ViYW83eS9vanlqMTREcWlFREtUV3dhODY2NjBWVFZDWkRDWEhGSGVCdkdNb1I2CkFwNm9sVmxNZnMwa1BxMWFaQTZ4V3Y0RERhRXFVdDlvZjl2MDVhTnZ0UGVOM2dHMGVyWTh1anJ6djZqV1R3L2YKSU5DREdKMWJmbjNXTERHUlNtMU53TndQbThMMWJRWjUwcnB1Tmx2Z0NnU1ZrblJpSzlRK3dYbzlZMkoxMERqYgpESnJCd1ZKcCs0aW14NHhkU016SHhxdzlGR2V2QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTeFVMUysxNExkL2R4RUN1SzhzcENGUmZSNjBEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRGdRN2VVejliYQpHd0psVGdmY2NJbkd2MUVMRGlmaXBzNEZlcDNrelhtNVdPU3JrY2lQUGFyR3dJV3o5OW1meHZKSzJ1cjVMeWRXCnlraGt1K0REL3VUVzdQVjMweTVDa0dEQzlUQm50cUROanhVUThRR1ZQaFp0Wm53a25vQ1dDNWhubGNHS01ueVgKUFpYSDNNZkxOY2I1OXBBWnE4elBOV2FrbVdINTYwMzRwOVVRYWZWUmlQc3JaL21YeDc5ZjRDNHJJcm8yUzZjcAorcTQwZ2ZsalVRcFZSQXRTK1Nxek5JWXZ2ajhKdDh4UjVVdGlJN3IxWit1emJxZGFUWkt5bkxXaXJjREQ1QjlmCjRXdTdodXpyZ3o5YWlJeUJkSkxFNEZrOTZpdUh4VVdCdHZidmJKMHBoUWUwUmdYeWpzMm1JRXB4UkpDS0o4WE8KdUxjbUgwT3dKV3JQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://ab1b8b69-64f0-4fe0-bf7c-e5f83c7c6fad.us-sea-1-gw.linodelke.net:443
  name: lke570723

users:
- name: lke570723-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im9OV2ExMnZyaVV5eUc2NmNQVy1FRU83bTlKU0dnZERMTE9UNzBDV3k4NG8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tNXBsangiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYjg2MDM5MWItYTFkMC00ZDVjLTllYTAtY2M2YmY0ZjU2YzM2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.FE-j0DmoJHxS-Hi3HOUl5wlerpKvFnwOxUqEjL3p5tQlg6i7qbih4oFWTZCz-km9xk6bqPUgXICCdBV00c0L4K0zVX7FaoViTeVxclRM_YiRiseclw1yEZ77KiO7fLJfipDaBPmu8FPRLYfeXTt31DtOrKPs8TCMDLXGvN1Z3vf1fxzuSsbqr0Zuf3NrbRaNqxSCPhDUEuXH_P0ftEUK9oC1qxQuOxiPmQWr7rCeEBdS0WUtbiYBQFXy_HUkz2EE8K6pGKmsrAMG22mJv-Zhr64pPXgXFXedDTEw2SUKQ6mnua7H7_uGJ3okgG6800Kva6Tx_n-QeDB6dl7DyG430A

contexts:
- context:
    cluster: lke570723
    namespace: default
    user: lke570723-admin
  name: lke570723-ctx

current-context: lke570723-ctx
